export const actionType ={
    BASICINFO: 'BASICINFO',
    CONTACTINFO: 'CONTACTINFO',
    CUSTOMERBASIC: 'CUSTOMERBASIC',
    CUSTOMERDETAILS: 'CUSTOMERDETAILS',
    EMPDETAILS: 'EMPDETAILS',
    LEAVEREQUEST: 'LEAVEREQUEST',
    PAYMENTINFO: 'PAYMENTINFO',
    PERSONELINFO: 'PERSONELINFO',
    TEAMLEADER: 'TEAMLEADER',    
}

export const activeType ={
    ACTIVE_TAB: 'ACTIVE_TAB',    
    ACTIVE_STEP: 'ACTIVE_STEP',
}